using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using MauiApp1.Models;

namespace MauiApp1.Services;

public class PdfExportService
{
    public void Export(string outputPath, List<JournalEntry> entries)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(20);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("JournalDesk Export")
                    .FontSize(18).SemiBold();

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    foreach (var e in entries.OrderBy(x => x.EntryDate))
                    {
                        col.Item().Border(1).Padding(10).Column(card =>
                        {
                            card.Item().Text($"{e.EntryDate:yyyy-MM-dd} — {e.Title}")
                                .FontSize(14).SemiBold();

                            card.Item().Text($"Primary Mood Id: {e.PrimaryMoodId}");
                            card.Item().Text($"Created: {e.CreatedAt:yyyy-MM-dd HH:mm}   Updated: {e.UpdatedAt:yyyy-MM-dd HH:mm}");

                            card.Item().LineHorizontal(1);

                            card.Item().Text(e.Content ?? "").FontSize(11);
                        });
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by JournalDesk • ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        })
        .GeneratePdf(outputPath);
    }
}
